SELECT name 
FROM pizzeria
WHERE id NOT IN (SELECT pizzeria_id AS id FROM person_visits);

SELECT NAME
FROM PIZZERIA
WHERE NOT EXISTS
		(SELECT PIZZERIA_ID
			FROM PERSON_VISITS
			WHERE PIZZERIA.ID = PIZZERIA_ID);