SELECT PERSON.NAME AS PERSON_NAME,
	PIZZA_NAME,
	PIZZERIA.NAME AS PIZZERIA_NAME
FROM PERSON
INNER JOIN PERSON_ORDER ON PERSON_ID = PERSON.ID
INNER JOIN MENU ON MENU_ID = MENU.ID
INNER JOIN PIZZERIA ON MENU.PIZZERIA_ID = PIZZERIA.ID
ORDER BY 1 ASC,
	2 ASC,
	3 ASC;