
SELECT ORDER_DATE,
	PERSON_INFORMATION
FROM
	(SELECT NAME || ' (age:' || AGE || ')' AS PERSON_INFORMATION,
			ID
		FROM PERSON) AS TABLE1
INNER JOIN PERSON_ORDER ON PERSON_ORDER.PERSON_ID = TABLE1.ID
ORDER BY 1 ASC,
	2 ASC;