SELECT ORDER_DATE,
	PERSON_INFORMATION
FROM
	(SELECT NAME || ' (age:' || AGE || ')' AS PERSON_INFORMATION,
			ID
		FROM PERSON) AS TABLE1
NATURAL JOIN (SELECT order_date, person_id AS ID FROM PERSON_ORDER) AS nj
ORDER BY 1 ASC,
	2 ASC;