SELECT ACTION_DATE,
	PERSON.NAME
FROM
	(SELECT ORDER_DATE AS ACTION_DATE,
			PERSON_ID
		FROM PERSON_ORDER 
    INTERSECT 
    SELECT VISIT_DATE AS ACTION_DATE,
			PERSON_ID
		FROM PERSON_VISITS) AS INTER
INNER JOIN PERSON ON PERSON.ID = PERSON_ID
ORDER BY 1 ASC,
	2 DESC;